export { default as Municipalities, MunicipalityType } from '@/components/areas/municipalities'
export { default as Constituencies, ConstituencyType } from '@/components/areas/constituencies'
export { default as Regions, RegionType } from '@/components/areas/regions'
export { default as Islands, IslandType } from '@/components/areas/islands'
export { default as Denmark, DenmarkType } from '@/components/areas/denmark'
